# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2decf812878760b4125cac4d45c34256a183d02b4a5e94a4a6908db86dbdb1c0f7f0709720a0d7c3c1bbc56c3ff2ee1a138f1108c6afee59cd37e53de0cbb69c

test:
  secret_key_base: 5aa21c5c3466dfba878813d6347823533d21c9178fcff43aea8ae066085b28f71ed9c71dd40a7ca469a11ecb1a1a72709226b92281cff6dc94dbd5639f24c693

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
